---
# Format and mount openstack volume

- name: storage volume | install xfs
  become: true
  ansible.builtin.dnf:
    pkg: xfsprogs
    state: present

- name: storage volume | format
  become: true
  ansible.builtin.filesystem:
    fstype: xfs
    dev: "{{ storage_volume_initialise_device }}"

- name: storage volume | mount
  become: true
  ansible.builtin.mount:
    fstype: xfs
    name: "{{ storage_volume_initialise_mount }}"
    opts: noatime
    src: "{{ storage_volume_initialise_device }}"
    state: mounted
